[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'

[tool.flake8]
max-line-length = 100
exclude = [".git", "__pycache__", "build", "dist", "*/python/*", "*/vendored/*", "*/.venv/*"]
ignore = ["E203", "W503", "E501"]
per-file-ignores = ["__init__.py:F401"]